### ISSUE TITLE
Contact Bike Walk Durham

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/BikeSafety#36]
They have serveral 'durham improvement plans' mapped out - its all rather old data, but it could be interesting to reach out and see where that data came from.

http://www.bikewalkdurham.org/BPAC_maps.html

**Comment by gt150** [comment]
Test

**Comment by gt150** [comment]
Sent email on August 11.

**Comment by gt150** [comment]
Received a response from bikewalkdurham sharing their data sources and providing some suggestions of additional data.

**Comment by dsummersl** [comment]
Ah nice, thanks for reaching out to them - post the details here maybe?

**Comment by gt150** [comment]
Email responses from bikewalkdurham:

From Dale @ bikewalkdurham
The "existing crashes database" put together by the Durham Bicycle and Pedestrian Advisory Commission that (I think) you are referring to has the same source (NCDMV crash reports collected from law enforcement agencies) as the information NC Bike Crash Data that you are already collecting.  So it’s the same information.

Furthermore, the NC Bike Crash Data file is superior to the BPAC data because the location of each crash has been geocoded.

The previous maps by BPAC generally showed the location of the crash as being at the nearest intersection, so some crashes that were occurring on private property (parking lots, for instance) were showing up as being on a public street.

Please note that one of the Durham cyclists who was killed over the past year was actually riding in Chapel Hill.

Please let me know if you have questions about what I am trying to say.

It might also be interesting to collect data from emergency rooms as was done in Asheville. 

---

From Dale @bikewalkdurham
NCDOT has put out a bike/ped crash map that can be viewed here (I thought I had sent this out before, but maybe did not):

https://ncdot.maps.arcgis.com/home/webmap/viewer.html?webmap=b4fcdc266d054a1ca075b60715f88aef

This map is superior to the map previously produced by BPAC because (1) the location of each crash has been geocoded and (2) you can click on each crash and get additional details.

The previous map by BPAC generally showed the location of the crash as being at the nearest intersection, so some crashes that were occurring on private property (parking lots, for instance) were showing up as being on a public street.

We have existing sidewalk and bike lane GIS files.  I’ll ask why they aren’t on the Open Durham site.
